databases:
  - name: roobinhud
    databaseName: roobinhud
    user: roobinhud

services:
  - type: web
    name: roobinhud
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: roobinhud
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false